# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cindy Wang Computer Ethics Blog
email: xwang29@nd.edu
name: Cindy Wang Computer Ethics Blog
description: > # this means to ignore newlines until "baseurl:"
  I keep the blog posts for discussions in Ethical and Social Issues for Computer Science
  class.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cindyxinyiwang.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  cindyxinyiwang

# Build settings
markdown: kramdown
